# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38f1a59abd145a2e0cbef0567c238c6490e3df400c1ecf5bba2c4dfc8058b326f5d56b582824f9576ca2d6684f6280a4c9d616b4748c96c0735d112b5ffdd159

test:
  secret_key_base: 3865bbbe6400940f91ad93d3251160e355004db6b60cb22b655f183de81629e316dd5b21be4e29857f60964902011eb1bbbe308b26c4112204121da68d5c02b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
