validates:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  content:
    max_length: 140
limit_size:
  width: 400
  height: 400
gravatar_size:
  small: 30
  medium: 50
  large: 80
max_size_in_mb:  5
